# Generated by Django 5.1.7 on 2025-03-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Naziv projekta')),
                ('short_description', models.CharField(max_length=500, verbose_name='Kratak opis')),
                ('long_description', models.TextField(verbose_name='Dug opis')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Datum')),
                ('main_image', models.ImageField(upload_to='projects/main_images/', verbose_name='Glavna slika')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/secondary_images/', verbose_name='Sporedna slika')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.project')),
            ],
        ),
    ]
