# Generated by Django 5.1.7 on 2025-03-21 14:49

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(upload_to=website.models.project_image_upload_path, verbose_name='Glavna slika'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=website.models.project_image_upload_path, verbose_name='Sporedna slika'),
        ),
    ]
