# Generated by Django 5.1.7 on 2025-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_project_main_image_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('adaptation', 'Adaptation')], default='adaptation', max_length=20),
        ),
    ]
