# Generated by Django 5.1.7 on 2025-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_project_contact_alter_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planirano'), ('active', 'Aktivno'), ('paused', 'Pauzirano'), ('completed', 'Završeno'), ('cancelled', 'Otkazano')], default='planned', max_length=20),
        ),
    ]
