# Generated by Django 5.1.7 on 2025-07-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_project_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advance',
            old_name='date_received',
            new_name='date',
        ),
    ]
