# Generated by Django 5.1.7 on 2025-07-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_rename_date_received_advance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='advance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='construction.project'),
        ),
    ]
