# Generated by Django 5.1.7 on 2025-07-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kom', 'Komad'), ('kg', 'Kilogram'), ('m', 'Metar'), ('m2', 'Metar kvadratni'), ('m3', 'Metar kubni'), ('l', 'Litar')], max_length=10)),
                ('price', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.project')),
            ],
        ),
    ]
