# Generated by Django 5.1.7 on 2025-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0015_remove_worker_project_rate_worker_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
